In [1]:
import numpy as np
import pandas as pd

In [2]:
#loading train and testing data

loaded_train = np.load('30k_data.npz')

loaded_test = np.load('10k_test_data.npz')

In [3]:
loaded_train.files

['arr_0']

In [4]:
loaded_test.files

['arr_0']

In [5]:
#extract train dataset
Train = loaded_train['arr_0']

In [6]:
#extract test dataset
Test = loaded_test['arr_0']

In [7]:
#create test dataframe
Test_df = pd.DataFrame(Test)

In [8]:
#creating the X_Test and y_test
X_Test = Test_df.iloc[:, 0:-1]
y_test = Test_df.iloc[:, -1]


In [9]:
X_Test.shape

(10000, 2381)

In [10]:
y_test.shape

(10000,)

In [11]:
Test_df.shape

(10000, 2382)

In [12]:
#create train dataframe
Train_df = pd.DataFrame(Train)

In [13]:
#creating the X_Train and y_train
X_Train = Train_df.iloc[:, 0:-1]
y_train = Train_df.iloc[:, -1]

In [14]:
Train_df.shape

(30000, 2382)

In [15]:
X_Train.shape

(30000, 2381)

In [16]:
y_train.shape

(30000,)

In [17]:
#Scaling 

from sklearn import preprocessing

scaler_1 = preprocessing.StandardScaler().fit(X_Train)
X_Train_scaled = scaler_1.transform(X_Train) 

# test data
scaler_2 = preprocessing.StandardScaler().fit(X_Test)
X_Test_scaled = scaler_2.transform(X_Test)

In [18]:
X_Train_scaled

array([[-1.1376668 , -0.71354455, -0.4002507 , ..., -0.0206471 ,
        -0.02642179, -0.0147915 ],
       [-1.1344174 , -0.716158  , -0.39651167, ..., -0.0206471 ,
        -0.02642179, -0.0147915 ],
       [-1.1223845 , -0.71412957, -0.4013139 , ..., -0.0206471 ,
        -0.02642179, -0.0147915 ],
       ...,
       [ 0.16267364,  0.89384055,  0.00172271, ..., -0.0206471 ,
        -0.02642179, -0.0147915 ],
       [-1.1528703 , -0.73119855, -0.38722658, ..., -0.0206471 ,
        -0.02642179, -0.0147915 ],
       [-0.44064534, -0.50288445, -0.20090239, ..., -0.0206471 ,
        -0.02642179, -0.0147915 ]], dtype=float32)

In [19]:
#loading the features names

feature_names = np.genfromtxt("ember_2381_feature_names.txt", delimiter=",", dtype='str', comments="!#", invalid_raise=False)

In [20]:
feature_names_df = pd.DataFrame(feature_names)

In [21]:
feature_names_df

0
0                          ByteHistorgram-0
1                          ByteHistorgram-1
2                          ByteHistorgram-2
3                          ByteHistorgram-3
4                          ByteHistorgram-4
...                                     ...
2377          size of data directories - 13
2378  virtual size of data directories - 13
2379          size of data directories - 14
2380  virtual size of data directories - 14
2381                                 labels

[2382 rows x 1 columns]

In [22]:
feature_names_df = feature_names_df.drop(2381, axis=0)

In [23]:
X_Train_scaled_df = pd.DataFrame(X_Train_scaled)

In [24]:
X_Train_scaled_df.shape

(30000, 2381)

In [25]:
feature_names_df.shape

(2381, 1)

In [26]:
X_Train_scaled_df.columns = feature_names_df

In [27]:
X_Train_scaled_df.head()

(ByteHistorgram-0,)  (ByteHistorgram-1,)  (ByteHistorgram-2,)  \
0            -1.137667            -0.713545            -0.400251   
1            -1.134417            -0.716158            -0.396512   
2            -1.122385            -0.714130            -0.401314   
3             0.636686             2.368200            -0.214936   
4             0.563951            -0.055217            -0.333835   

   (ByteHistorgram-3,)  (ByteHistorgram-4,)  (ByteHistorgram-5,)  \
0            -0.250323            -0.341734            -0.055461   
1            -0.240663            -0.337414            -0.055016   
2            -0.244660            -0.334247            -0.067405   
3            -0.281234            -0.122502            -0.063992   
4             0.244784            -0.095730            -0.199279   

   (ByteHistorgram-6,)  (ByteHistorgram-7,)  (ByteHistorgram-8,)  \
0            -0.146172             0.100514            -0.550944   
1            -0.134112             0.083309            -0.563923   
2            -0.138085             0.111495            -0.539702   
3            -0.502543             0.244888            -0.542948   
4            -0.389021            -0.358985             0.752980   

   (ByteHistorgram-9,)  ...  (size of data directories - 10,)  \
0             0.145270  ...                         -0.016308   
1             0.135229  ...                         -0.016308   
2             0.153068  ...                         -0.016308   
3            -0.314072  ...                         -0.016307   
4            -0.358740  ...                         -0.016308   

   (virtual size of data directories - 10,)  (size of data directories - 11,)  \
0                                 -0.020853                         -0.016188   
1                                 -0.020853                         -0.016188   
2                                 -0.020853                         -0.016188   
3                                 -0.020754                         -0.016184   
4                                 -0.020853                         -0.016187   

   (virtual size of data directories - 11,)  (size of data directories - 12,)  \
0                                 -0.010345                         -0.005820   
1                                 -0.010345                         -0.005820   
2                                 -0.010345                         -0.005820   
3                                 -0.010319                         -0.005803   
4                                 -0.010320                         -0.005804   

   (virtual size of data directories - 12,)  (size of data directories - 13,)  \
0                                 -0.022133                         -0.016176   
1                                 -0.022133                         -0.016176   
2                                 -0.022133                         -0.016176   
3                                 -0.022067                         -0.016176   
4                                 -0.020923                         -0.016176   

   (virtual size of data directories - 13,)  (size of data directories - 14,)  \
0                                 -0.020647                         -0.026422   
1                                 -0.020647                         -0.026422   
2                                 -0.020647                         -0.026422   
3                                 -0.020647                         -0.026422   
4                                 -0.020647                         -0.026422   

   (virtual size of data directories - 14,)  
0                                 -0.014791  
1                                 -0.014791  
2                                 -0.014791  
3                                 -0.014791  
4                                 -0.014791  

[5 rows x 2381 columns]

# Feature Selection- Dropping constant features - Variance Threshold

In [28]:
from sklearn.feature_selection import VarianceThreshold


#threshold 0.0
selector = VarianceThreshold(threshold=0)
selector.fit(X_Train_scaled_df)

VarianceThreshold(threshold=0)

In [29]:
### Finding non constant features

sum(selector.get_support())

2333

In [42]:
#threshold 0.1
selector_1 = VarianceThreshold(threshold=1)
selector_1.fit(X_Train_scaled_df)

VarianceThreshold(threshold=1)

In [43]:
sum(selector_1.get_support())

1184

# Feature Selection- With Correlation

In [44]:
X_Train_scaled_df.corr()

(ByteHistorgram-0,)  \
(ByteHistorgram-0,)                                  1.000000   
(ByteHistorgram-1,)                                  0.077799   
(ByteHistorgram-2,)                                  0.007582   
(ByteHistorgram-3,)                                 -0.068633   
(ByteHistorgram-4,)                                 -0.002758   
...                                                       ...   
(virtual size of data directories - 12,)             0.014661   
(size of data directories - 13,)                     0.015601   
(virtual size of data directories - 13,)             0.011685   
(size of data directories - 14,)                    -0.009976   
(virtual size of data directories - 14,)             0.006945   

                                          (ByteHistorgram-1,)  \
(ByteHistorgram-0,)                                  0.077799   
(ByteHistorgram-1,)                                  1.000000   
(ByteHistorgram-2,)                                  0.471931   
(ByteHistorgram-3,)                                  0.257311   
(ByteHistorgram-4,)                                  0.200757   
...                                                       ...   
(virtual size of data directories - 12,)            -0.007896   
(size of data directories - 13,)                    -0.008864   
(virtual size of data directories - 13,)            -0.009126   
(size of data directories - 14,)                    -0.017631   
(virtual size of data directories - 14,)            -0.008001   

                                          (ByteHistorgram-2,)  \
(ByteHistorgram-0,)                                  0.007582   
(ByteHistorgram-1,)                                  0.471931   
(ByteHistorgram-2,)                                  1.000000   
(ByteHistorgram-3,)                                  0.266891   
(ByteHistorgram-4,)                                  0.207223   
...                                                       ...   
(virtual size of data directories - 12,)             0.005447   
(size of data directories - 13,)                     0.005388   
(virtual size of data directories - 13,)             0.005698   
(size of data directories - 14,)                    -0.006323   
(virtual size of data directories - 14,)             0.002688   

                                          (ByteHistorgram-3,)  \
(ByteHistorgram-0,)                                 -0.068633   
(ByteHistorgram-1,)                                  0.257311   
(ByteHistorgram-2,)                                  0.266891   
(ByteHistorgram-3,)                                  1.000000   
(ByteHistorgram-4,)                                  0.128278   
...                                                       ...   
(virtual size of data directories - 12,)            -0.001842   
(size of data directories - 13,)                    -0.001701   
(virtual size of data directories - 13,)            -0.001598   
(size of data directories - 14,)                    -0.008817   
(virtual size of data directories - 14,)            -0.001807   

                                          (ByteHistorgram-4,)  \
(ByteHistorgram-0,)                                 -0.002758   
(ByteHistorgram-1,)                                  0.200757   
(ByteHistorgram-2,)                                  0.207223   
(ByteHistorgram-3,)                                  0.128278   
(ByteHistorgram-4,)                                  1.000000   
...                                                       ...   
(virtual size of data directories - 12,)            -0.006139   
(size of data directories - 13,)                    -0.006280   
(virtual size of data directories - 13,)            -0.006638   
(size of data directories - 14,)                    -0.012969   
(virtual size of data directories - 14,)            -0.005387   

                                          (ByteHistorgram-5,)  \
(ByteHistorgram-0,)                                 -0.126240   
(ByteHi

In [45]:
# with the following function we can select highly correlated features
# it will remove the first feature that is correlated with anything other feature

def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [48]:
corr_features = correlation(X_Train_scaled_df, 0.5)
len(set(corr_features))

935

In [49]:
corr_features_1 = correlation(X_Train_scaled_df, 0.6)
len(set(corr_features_1))

670

In [50]:
corr_features_2 = correlation(X_Train_scaled_df, 0.7)
len(set(corr_features_2))

501

In [51]:
corr_features_3 = correlation(X_Train_scaled_df, 0.8)
len(set(corr_features_3))

392

In [52]:
corr_features_4 = correlation(X_Train_scaled_df, 0.9)
len(set(corr_features_4))

310

In [53]:
corr_features_5 = correlation(X_Train_scaled_df, 0.85)
len(set(corr_features_5))

350

# Feature Selection-Information gain - mutual information

In [54]:
from sklearn.feature_selection import mutual_info_classif

# determine the mutual information
mutual_info = mutual_info_classif(X_Train_scaled_df, y_train)
mutual_info

array([0.15812959, 0.17333583, 0.14454224, ..., 0.04024201, 0.0329049 ,
       0.03291611])

In [55]:
mutual_info = pd.Series(mutual_info)
mutual_info.index =X_Train_scaled_df.columns
mutual_info.sort_values(ascending=False)

(virtual size of data directories - 1,)                  0.263923
(size of data directories - 2,)                          0.252010
(when the file was created,)                             0.245299
(hash on pair of section name and virtual size - 43,)    0.224090
(hash on pair of section name and entropy - 43,)         0.219444
                                                           ...   
(hash on list of properties of entry point - 25,)        0.000000
(hash on list of library:function - 126,)                0.000000
(hash optional dll_characteristics - 6,)                 0.000000
(hash on list of library:function - 128,)                0.000000
(hash on list of library:function - 860,)                0.000000
Length: 2381, dtype: float64

In [56]:
from sklearn.feature_selection import SelectKBest

In [57]:
#No we Will select the  top 5 important features
sel_100_cols = SelectKBest(mutual_info_classif, k=100)
sel_100_cols.fit(X_Train_scaled_df, y_train)
X_Train_scaled_df.columns[sel_100_cols.get_support()]

Index([                                  ('ByteHistorgram-1',),
                                        ('ByteHistorgram-32',),
                                       ('ByteHistorgram-101',),
                                       ('ByteHistorgram-106',),
                                       ('ByteHistorgram-114',),
                                       ('ByteHistorgram-116',),
                                       ('ByteHistorgram-127',),
                                       ('ByteHistorgram-137',),
                                       ('ByteHistorgram-139',),
                                       ('ByteHistorgram-141',),
                                       ('ByteHistorgram-142',),
                                       ('ByteHistorgram-155',),
                                       ('ByteHistorgram-157',),
                                       ('ByteHistorgram-158',),
                                       ('ByteHistorgram-159',),
                                       (

# Feature Selection - Univariate feature selection - F-test

In [59]:
from sklearn.feature_selection import f_classif


f_cl_100_cols = SelectKBest(f_classif, k=100).fit(X_Train_scaled_df, y_train)

X_Train_scaled_df.columns[f_cl_100_cols.get_support()]

C:\Users\Ngobi\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [627 629 636 638 648 650 652 659 663 666 667 669 670 672 673 674 675 676
 849 859 862 867 883 891 894 896 898 899 900 904 905 908 909 910 912 917
 919 920 922 923 924 925 926 931 932 934 936 937] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\Users\Ngobi\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


Index([                                ('ByteHistorgram-1',),
                                      ('ByteHistorgram-74',),
                                      ('ByteHistorgram-90',),
                                      ('ByteHistorgram-94',),
                                      ('ByteHistorgram-97',),
                                     ('ByteHistorgram-101',),
                                     ('ByteHistorgram-105',),
                                     ('ByteHistorgram-110',),
                                     ('ByteHistorgram-111',),
                                     ('ByteHistorgram-114',),
                                     ('ByteHistorgram-115',),
                                     ('ByteHistorgram-116',),
                                     ('ByteHistorgram-150',),
                                     ('ByteHistorgram-151',),
                                     ('ByteHistorgram-152',),
                                     ('ByteHistorgram-154',),
        

In [60]:
univ_f_classif = f_classif(X_Train_scaled_df, y_train)

univ_f_classif 

C:\Users\Ngobi\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [627 629 636 638 648 650 652 659 663 666 667 669 670 672 673 674 675 676
 849 859 862 867 883 891 894 896 898 899 900 904 905 908 909 910 912 917
 919 920 922 923 924 925 926 931 932 934 936 937] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\Users\Ngobi\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


(array([ 766.9451   , 2010.4202   ,  932.08954  , ...,    9.509689 ,
          21.075314 ,    6.2023115], dtype=float32),
 array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 2.0457536e-03,
        4.4337035e-06, 1.2763726e-02], dtype=float32))