In [1]:
import numpy as np

In [2]:
#loading compressed numpy files
loaded = np.load('New_Data.npz') 

In [3]:
loaded.files

['arr_0', 'arr_1']

In [4]:
#extract train dataset
Train_Data = loaded['arr_0']

In [5]:
#extract test dataset
Test_Data = loaded['arr_1']

In [6]:
Train_Data

array([[0.01467612, 0.00422187, 0.00392268, ..., 0.        , 0.        ,
        0.        ],
       [0.18452372, 0.0313075 , 0.00569281, ..., 0.        , 0.        ,
        0.        ],
       [0.25173673, 0.01420455, 0.00684149, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1429707 , 0.0086627 , 0.00420157, ..., 0.        , 0.        ,
        0.        ],
       [0.14780925, 0.00640215, 0.00511573, ..., 0.        , 0.        ,
        1.        ],
       [0.13445158, 0.00681443, 0.00554963, ..., 0.        , 0.        ,
        1.        ]], dtype=float32)

In [7]:
Train_Data.shape

(800000, 2382)

In [8]:
Test_Data

array([[5.6624603e-02, 8.2971752e-03, 6.1659808e-03, ..., 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [2.9683110e-01, 9.4364462e-03, 5.1571280e-03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [6.0806537e-01, 5.1895231e-03, 2.7639486e-03, ..., 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       ...,
       [1.6285709e-01, 7.4037062e-03, 2.9943257e-03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.3282295e-01, 2.1358723e-02, 1.0550695e-02, ..., 7.2000000e+01,
        8.2000000e+03, 0.0000000e+00],
       [4.9441105e-01, 4.2067310e-03, 2.0582932e-03, ..., 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00]], dtype=float32)

In [9]:
Test_Data.shape

(200000, 2382)

In [10]:
#import pandas

import pandas as pd

In [11]:
Train_Data_df = pd.DataFrame(Train_Data)

In [12]:
Train_Data_df.head()

0         1         2         3         4         5         6     \
0  0.014676  0.004222  0.003923  0.004029  0.004007  0.003775  0.003825   
1  0.184524  0.031308  0.005693  0.005959  0.008144  0.003512  0.005786   
2  0.251737  0.014205  0.006841  0.008556  0.023493  0.002858  0.003401   
3  0.008964  0.004055  0.003925  0.003936  0.004037  0.003878  0.003847   
4  0.020401  0.005213  0.004519  0.004097  0.004240  0.004029  0.003785   

       7         8         9     ...     2372   2373   2374    2375     2376  \
0  0.003887  0.004153  0.003804  ...  35240.0    0.0    0.0   660.0  32768.0   
1  0.008550  0.009141  0.001791  ...  92936.0  408.0  608.0  2604.0   4096.0   
2  0.008556  0.010215  0.001176  ...      0.0    0.0    0.0  1120.0   4096.0   
3  0.003946  0.003939  0.003834  ...      0.0    0.0    0.0     0.0      0.0   
4  0.004593  0.004875  0.003780  ...      0.0    0.0    0.0   520.0   4096.0   

    2377      2378  2379  2380  2381  
0    0.0       0.0   0.0   0.0   0.0  
1  224.0  442296.0   0.0   0.0   0.0  
2  192.0   37280.0   0.0   0.0   0.0  
3    0.0       0.0   0.0   0.0   0.0  
4    0.0       0.0   0.0   0.0   0.0  

[5 rows x 2382 columns]

In [13]:
#loading the features names

feature_names = np.genfromtxt("ember_2381_feature_names.txt", delimiter=",", dtype='str', comments="!#", invalid_raise=False)

In [14]:
feature_names

array(['ByteHistorgram-0', 'ByteHistorgram-1', 'ByteHistorgram-2', ...,
       'size of data directories - 14',
       'virtual size of data directories - 14', 'labels'], dtype='<U65')

In [15]:
feature_names_df = pd.DataFrame(feature_names)

In [16]:
feature_names_df

0
0                          ByteHistorgram-0
1                          ByteHistorgram-1
2                          ByteHistorgram-2
3                          ByteHistorgram-3
4                          ByteHistorgram-4
...                                     ...
2377          size of data directories - 13
2378  virtual size of data directories - 13
2379          size of data directories - 14
2380  virtual size of data directories - 14
2381                                 labels

[2382 rows x 1 columns]

In [17]:
Train_Data_df.shape

(800000, 2382)

In [18]:
feature_names_df.shape

(2382, 1)

In [19]:
Train_Data_df.columns = feature_names_df

In [20]:
Train_Data_df.head()

(ByteHistorgram-0,)  (ByteHistorgram-1,)  (ByteHistorgram-2,)  \
0             0.014676             0.004222             0.003923   
1             0.184524             0.031308             0.005693   
2             0.251737             0.014205             0.006841   
3             0.008964             0.004055             0.003925   
4             0.020401             0.005213             0.004519   

   (ByteHistorgram-3,)  (ByteHistorgram-4,)  (ByteHistorgram-5,)  \
0             0.004029             0.004007             0.003775   
1             0.005959             0.008144             0.003512   
2             0.008556             0.023493             0.002858   
3             0.003936             0.004037             0.003878   
4             0.004097             0.004240             0.004029   

   (ByteHistorgram-6,)  (ByteHistorgram-7,)  (ByteHistorgram-8,)  \
0             0.003825             0.003887             0.004153   
1             0.005786             0.008550             0.009141   
2             0.003401             0.008556             0.010215   
3             0.003847             0.003946             0.003939   
4             0.003785             0.004593             0.004875   

   (ByteHistorgram-9,)  ...  (virtual size of data directories - 10,)  \
0             0.003804  ...                                   35240.0   
1             0.001791  ...                                   92936.0   
2             0.001176  ...                                       0.0   
3             0.003834  ...                                       0.0   
4             0.003780  ...                                       0.0   

   (size of data directories - 11,)  (virtual size of data directories - 11,)  \
0                               0.0                                       0.0   
1                             408.0                                     608.0   
2                               0.0                                       0.0   
3                               0.0                                       0.0   
4                               0.0                                       0.0   

   (size of data directories - 12,)  (virtual size of data directories - 12,)  \
0                             660.0                                   32768.0   
1                            2604.0                                    4096.0   
2                            1120.0                                    4096.0   
3                               0.0                                       0.0   
4                             520.0                                    4096.0   

   (size of data directories - 13,)  (virtual size of data directories - 13,)  \
0                               0.0                                       0.0   
1                             224.0                                  442296.0   
2                             192.0                                   37280.0   
3                               0.0                                       0.0   
4                               0.0                                       0.0   

   (size of data directories - 14,)  (virtual size of data directories - 14,)  \
0                               0.0                                       0.0   
1                               0.0                                       0.0   
2                               0.0                                       0.0   
3                               0.0                                       0.0   
4                               0.0                                       0.0   

   (labels,)  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  

[5 rows x 2382 columns]

In [21]:
for col in Train_Data_df.columns:
    print(col)

('ByteHistorgram-0',)
('ByteHistorgram-1',)
('ByteHistorgram-2',)
('ByteHistorgram-3',)
('ByteHistorgram-4',)
('ByteHistorgram-5',)
('ByteHistorgram-6',)
('ByteHistorgram-7',)
('ByteHistorgram-8',)
('ByteHistorgram-9',)
('ByteHistorgram-10',)
('ByteHistorgram-11',)
('ByteHistorgram-12',)
('ByteHistorgram-13',)
('ByteHistorgram-14',)
('ByteHistorgram-15',)
('ByteHistorgram-16',)
('ByteHistorgram-17',)
('ByteHistorgram-18',)
('ByteHistorgram-19',)
('ByteHistorgram-20',)
('ByteHistorgram-21',)
('ByteHistorgram-22',)
('ByteHistorgram-23',)
('ByteHistorgram-24',)
('ByteHistorgram-25',)
('ByteHistorgram-26',)
('ByteHistorgram-27',)
('ByteHistorgram-28',)
('ByteHistorgram-29',)
('ByteHistorgram-30',)
('ByteHistorgram-31',)
('ByteHistorgram-32',)
('ByteHistorgram-33',)
('ByteHistorgram-34',)
('ByteHistorgram-35',)
('ByteHistorgram-36',)
('ByteHistorgram-37',)
('ByteHistorgram-38',)
('ByteHistorgram-39',)
('ByteHistorgram-40',)
('ByteHistorgram-41',)
('ByteHistorgram-42',)
('ByteHistorgram-43',

('hash on list of library:function - 634',)
('hash on list of library:function - 635',)
('hash on list of library:function - 636',)
('hash on list of library:function - 637',)
('hash on list of library:function - 638',)
('hash on list of library:function - 639',)
('hash on list of library:function - 640',)
('hash on list of library:function - 641',)
('hash on list of library:function - 642',)
('hash on list of library:function - 643',)
('hash on list of library:function - 644',)
('hash on list of library:function - 645',)
('hash on list of library:function - 646',)
('hash on list of library:function - 647',)
('hash on list of library:function - 648',)
('hash on list of library:function - 649',)
('hash on list of library:function - 650',)
('hash on list of library:function - 651',)
('hash on list of library:function - 652',)
('hash on list of library:function - 653',)
('hash on list of library:function - 654',)
('hash on list of library:function - 655',)
('hash on list of library:functi

In [22]:
Train_Data_df[('labels',)].unique()

array([ 0.,  1., -1.], dtype=float32)

In [23]:
#drop unlabeled rows in labels column

Train_Data_df = Train_Data_df[Train_Data_df[('labels',)] != -1]

In [24]:
Train_Data_df.shape

(600000, 2382)

In [25]:
Train_Data_np = Train_Data_df.to_numpy()

In [26]:
np.savez_compressed('600k_data', Train_Data_np)

In [27]:
Train_Data_np

array([[0.01467612, 0.00422187, 0.00392268, ..., 0.        , 0.        ,
        0.        ],
       [0.18452372, 0.0313075 , 0.00569281, ..., 0.        , 0.        ,
        0.        ],
       [0.25173673, 0.01420455, 0.00684149, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1429707 , 0.0086627 , 0.00420157, ..., 0.        , 0.        ,
        0.        ],
       [0.14780925, 0.00640215, 0.00511573, ..., 0.        , 0.        ,
        1.        ],
       [0.13445158, 0.00681443, 0.00554963, ..., 0.        , 0.        ,
        1.        ]], dtype=float32)