In [1]:
import ember


In [2]:
data_dir = "ember2018" #path for the data


In [3]:
ember.create_vectorized_features(data_dir)
_ = ember.create_metadata(data_dir)

Vectorizing training set


100%|█████████████████████████████████████████████████████████████████████████| 800000/800000 [22:42<00:00, 587.25it/s]


Vectorizing test set


100%|█████████████████████████████████████████████████████████████████████████| 200000/200000 [06:15<00:00, 533.22it/s]


In [4]:
X_train, y_train, X_test, y_test = ember.read_vectorized_features(data_dir)   

In [5]:
X_train  #view the training data

memmap([[1.4676122e-02, 4.2218715e-03, 3.9226813e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [1.8452372e-01, 3.1307504e-02, 5.6928140e-03, ..., 4.4229600e+05,
         0.0000000e+00, 0.0000000e+00],
        [2.5173673e-01, 1.4204546e-02, 6.8414863e-03, ..., 3.7280000e+04,
         0.0000000e+00, 0.0000000e+00],
        ...,
        [1.4297070e-01, 8.6626979e-03, 4.2015705e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [1.4780925e-01, 6.4021470e-03, 5.1157344e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [1.3445158e-01, 6.8144272e-03, 5.5496283e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [6]:
X_train.shape   # size of the  data training

(800000, 2381)

In [7]:
y_train.shape

(800000,)

In [8]:
import numpy as np

In [9]:
new_array = np.concatenate((X_train, X_test), axis=0)    #Creating a single dataset from both the training and testing data

In [10]:
new_array

array([[1.4676122e-02, 4.2218715e-03, 3.9226813e-03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.8452372e-01, 3.1307504e-02, 5.6928140e-03, ..., 4.4229600e+05,
        0.0000000e+00, 0.0000000e+00],
       [2.5173673e-01, 1.4204546e-02, 6.8414863e-03, ..., 3.7280000e+04,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [1.6285709e-01, 7.4037062e-03, 2.9943257e-03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.3282295e-01, 2.1358723e-02, 1.0550695e-02, ..., 0.0000000e+00,
        7.2000000e+01, 8.2000000e+03],
       [4.9441105e-01, 4.2067310e-03, 2.0582932e-03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [11]:
new_array.shape

(1000000, 2381)

In [12]:
new_array_y = np.concatenate((y_train, y_test), axis=0)   #Creating a single vector for the labels

In [13]:
new_array_y

array([0., 0., 0., ..., 0., 0., 1.], dtype=float32)

In [14]:
new_array_y.shape

(1000000,)

In [15]:
np.unique(new_array_y)   #return unique values

array([-1.,  0.,  1.], dtype=float32)

In [16]:
(unique, counts) = np.unique(new_array_y, return_counts=True)     #return unique values and count
frequencies = np.asarray((unique, counts)).T

frequencies

array([[-1.e+00,  2.e+05],
       [ 0.e+00,  4.e+05],
       [ 1.e+00,  4.e+05]])

In [17]:
import numpy as np
import pandas as pd

In [18]:
X_train_data = pd.DataFrame(X_train)   #converting the array to dataframes

In [19]:
Y_train_data = pd.DataFrame(y_train)

In [20]:
X_test_data = pd.DataFrame(X_test)

In [21]:
Y_test_data = pd.DataFrame(y_test)

In [22]:
X_train_data.head()

0         1         2         3         4         5         6     \
0  0.014676  0.004222  0.003923  0.004029  0.004007  0.003775  0.003825   
1  0.184524  0.031308  0.005693  0.005959  0.008144  0.003512  0.005786   
2  0.251737  0.014205  0.006841  0.008556  0.023493  0.002858  0.003401   
3  0.008964  0.004055  0.003925  0.003936  0.004037  0.003878  0.003847   
4  0.020401  0.005213  0.004519  0.004097  0.004240  0.004029  0.003785   

       7         8         9     ...  2371     2372   2373   2374    2375  \
0  0.003887  0.004153  0.003804  ...  72.0  35240.0    0.0    0.0   660.0   
1  0.008550  0.009141  0.001791  ...  64.0  92936.0  408.0  608.0  2604.0   
2  0.008556  0.010215  0.001176  ...   0.0      0.0    0.0    0.0  1120.0   
3  0.003946  0.003939  0.003834  ...   0.0      0.0    0.0    0.0     0.0   
4  0.004593  0.004875  0.003780  ...   0.0      0.0    0.0    0.0   520.0   

      2376   2377      2378  2379  2380  
0  32768.0    0.0       0.0   0.0   0.0  
1   4096.0  224.0  442296.0   0.0   0.0  
2   4096.0  192.0   37280.0   0.0   0.0  
3      0.0    0.0       0.0   0.0   0.0  
4   4096.0    0.0       0.0   0.0   0.0  

[5 rows x 2381 columns]

In [23]:
Y_train_data

0
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
...     ...
799995  1.0
799996  1.0
799997  0.0
799998  1.0
799999  1.0

[800000 rows x 1 columns]

In [24]:
X_data = pd.DataFrame(new_array)

X_data.head()

0         1         2         3         4         5         6     \
0  0.014676  0.004222  0.003923  0.004029  0.004007  0.003775  0.003825   
1  0.184524  0.031308  0.005693  0.005959  0.008144  0.003512  0.005786   
2  0.251737  0.014205  0.006841  0.008556  0.023493  0.002858  0.003401   
3  0.008964  0.004055  0.003925  0.003936  0.004037  0.003878  0.003847   
4  0.020401  0.005213  0.004519  0.004097  0.004240  0.004029  0.003785   

       7         8         9     ...  2371     2372   2373   2374    2375  \
0  0.003887  0.004153  0.003804  ...  72.0  35240.0    0.0    0.0   660.0   
1  0.008550  0.009141  0.001791  ...  64.0  92936.0  408.0  608.0  2604.0   
2  0.008556  0.010215  0.001176  ...   0.0      0.0    0.0    0.0  1120.0   
3  0.003946  0.003939  0.003834  ...   0.0      0.0    0.0    0.0     0.0   
4  0.004593  0.004875  0.003780  ...   0.0      0.0    0.0    0.0   520.0   

      2376   2377      2378  2379  2380  
0  32768.0    0.0       0.0   0.0   0.0  
1   4096.0  224.0  442296.0   0.0   0.0  
2   4096.0  192.0   37280.0   0.0   0.0  
3      0.0    0.0       0.0   0.0   0.0  
4   4096.0    0.0       0.0   0.0   0.0  

[5 rows x 2381 columns]

In [25]:
X_data.shape

(1000000, 2381)

In [26]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_data)    #standardization of the data

X_scaled = scaler.transform(X_data)

X_scaled

array([[-1.0704042 , -0.6011297 , -0.41426557, ..., -0.01638052,
        -0.0187919 , -0.01027877],
       [-0.1315548 ,  1.6822934 , -0.18836163, ..., -0.00485229,
        -0.0187919 , -0.01027877],
       [ 0.23997179,  0.24044818, -0.04176831, ..., -0.01540884,
        -0.0187919 , -0.01027877],
       ...,
       [-0.25131926, -0.33288878, -0.53274214, ..., -0.01638052,
        -0.0187919 , -0.01027877],
       [ 0.13542402,  0.84357285,  0.43160006, ..., -0.01638052,
        -0.01879004, -0.00983389],
       [ 1.5813782 , -0.6024061 , -0.65219843, ..., -0.01638052,
        -0.0187919 , -0.01027877]], dtype=float32)

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



def fit_random_forest_classifier(X, y):
    '''
    INPUT: names are pretty self explanatory
    OUTPUT: none - prints the confusion matrix and accuracy
    '''
    #First let's create training and testing data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

    #We could grid search and tune, but let's just fit a simple model to see how it does
    #instantiate
    clf = RandomForestClassifier(n_estimators=100, max_depth=None)

    #fit
    clf.fit(X_train, y_train)

    #predict
    y_preds = clf.predict(X_test)

    #score
    acc = accuracy_score(y_test, y_preds)
    print(acc)
    return acc

In [ ]:
fit_random_forest_classifier(X_scaled, new_array_y)