In [1]:
import numpy as np
import pandas as pd

filename = 'bodmas.npz'
data = np.load(filename)
X = data['X']  # all the feature vectors
y = data['y']  # labels, 0 as benign, 1 as malicious

print(X.shape, y.shape)

(134435, 2381) (134435,)


In [2]:
np.unique(y)

array([0, 1])

In [3]:
X

array([[0.05674198, 0.00801749, 0.00776239, ..., 0.        , 0.        ,
        0.        ],
       [0.00706228, 0.00449971, 0.00449817, ..., 0.        , 0.        ,
        0.        ],
       [0.0209748 , 0.00469876, 0.00400208, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1423067 , 0.01637877, 0.01097404, ..., 0.        , 0.        ,
        0.        ],
       [0.14230758, 0.01637877, 0.01097404, ..., 0.        , 0.        ,
        0.        ],
       [0.1423067 , 0.01637877, 0.01097404, ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [4]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [5]:
X_data = pd.DataFrame(X)

X_data.head()

0         1         2         3         4         5         6     \
0  0.056742  0.008017  0.007762  0.005466  0.007762  0.004446  0.005430   
1  0.007062  0.004500  0.004498  0.004318  0.004410  0.004330  0.004265   
2  0.020975  0.004699  0.004002  0.004419  0.004214  0.003865  0.003973   
3  0.006482  0.003821  0.003788  0.003866  0.003734  0.003784  0.003884   
4  0.022135  0.003972  0.003834  0.003869  0.003759  0.003765  0.003777   

       7         8         9     ...  2371  2372  2373  2374   2375     2376  \
0  0.003061  0.009475  0.006305  ...   0.0   0.0   0.0   0.0    0.0      0.0   
1  0.004068  0.004391  0.004306  ...   0.0   0.0   0.0   0.0  120.0  16564.0   
2  0.004297  0.003921  0.004145  ...   0.0   0.0   0.0   0.0    0.0      0.0   
3  0.003937  0.003805  0.003809  ...   0.0   0.0   0.0   0.0  140.0  16384.0   
4  0.003863  0.003773  0.003798  ...   0.0   0.0   0.0   0.0    0.0      0.0   

   2377  2378  2379  2380  
0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0  

[5 rows x 2381 columns]

In [6]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_data)

X_scaled = scaler.transform(X_data)

X_scaled

array([[-0.60842377, -0.12217378,  0.1805374 , ..., -0.01712796,
        -0.08373784, -0.01359115],
       [-0.8692141 , -0.32849306, -0.28640357, ..., -0.01712796,
        -0.08373784, -0.01359115],
       [-0.7961812 , -0.31681883, -0.35736898, ..., -0.01712796,
        -0.08373784, -0.01359115],
       ...,
       [-0.15925756,  0.3682181 ,  0.6399592 , ..., -0.01712796,
        -0.08373784, -0.01359115],
       [-0.15925296,  0.3682181 ,  0.6399592 , ..., -0.01712796,
        -0.08373784, -0.01359115],
       [-0.15925756,  0.3682181 ,  0.6399592 , ..., -0.01712796,
        -0.08373784, -0.01359115]], dtype=float32)

In [7]:
X_scaled_data = pd.DataFrame(X_scaled)

X_scaled_data.head()

0         1         2         3         4         5         6     \
0 -0.608424 -0.122174  0.180537  0.037640  0.104279  0.074880  0.095710   
1 -0.869214 -0.328493 -0.286404 -0.149405 -0.299842  0.046777 -0.108178   
2 -0.796181 -0.316819 -0.357369 -0.133002 -0.323490 -0.065683 -0.159356   
3 -0.872262 -0.368316 -0.387939 -0.223022 -0.381233 -0.085246 -0.174898   
4 -0.790089 -0.359461 -0.381473 -0.222588 -0.378263 -0.089918 -0.193634   

       7         8         9     ...      2371      2372     2373      2374  \
0 -0.105049  0.986098  0.953684  ... -0.018853 -0.022043 -0.01347 -0.016921   
1  0.159002 -0.301954  0.343431  ... -0.018853 -0.022043 -0.01347 -0.016921   
2  0.219244 -0.420990  0.294160  ... -0.018853 -0.022043 -0.01347 -0.016921   
3  0.124733 -0.450524  0.191508  ... -0.018853 -0.022043 -0.01347 -0.016921   
4  0.105244 -0.458730  0.188095  ... -0.018853 -0.022043 -0.01347 -0.016921   

       2375      2376      2377      2378      2379      2380  
0 -0.013642 -0.023642 -0.012886 -0.017128 -0.083738 -0.013591  
1 -0.013640 -0.023253 -0.012886 -0.017128 -0.083738 -0.013591  
2 -0.013642 -0.023642 -0.012886 -0.017128 -0.083738 -0.013591  
3 -0.013640 -0.023257 -0.012886 -0.017128 -0.083738 -0.013591  
4 -0.013642 -0.023642 -0.012886 -0.017128 -0.083738 -0.013591  

[5 rows x 2381 columns]

In [8]:
from sklearn import random_projection

transformer = random_projection.SparseRandomProjection(eps = 0.5)

X_new_data = transformer.fit_transform(X_scaled)

X_new_data.shape

(134435, 566)

In [9]:
X_new_data

array([[ 0.18299921, -0.82088654, -0.72910802, ...,  0.0876474 ,
         0.51230418,  1.29891056],
       [-0.06866136, -0.32029337, -1.06678073, ..., -0.28809784,
        -0.32051027,  1.77390096],
       [ 1.71149791, -0.30056002,  0.21653413, ...,  2.15956795,
        -1.04558462,  0.15236057],
       ...,
       [-3.65323859, -1.31224582,  0.70775958, ..., -0.69912214,
         4.62709716,  0.93383087],
       [-3.65323859, -1.31224582,  0.70775958, ..., -0.69912214,
         4.62709716,  0.93382951],
       [-3.65323859, -1.31224582,  0.70775958, ..., -0.69926433,
         4.62709716,  0.93383087]])

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

def fit_random_forest_classifier(X, y):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
    
    clf = RandomForestClassifier(max_depth=None, random_state=42, n_estimators=100)
    
    clf.fit(X_train, y_train)
    
    y_preds = clf.predict(X_test)
    
    #score
    acc = accuracy_score(y_test, y_preds)
    print(acc)
    return acc
    

In [11]:
fit_random_forest_classifier(X_scaled, y)

0.994594728620664


0.994594728620664

In [12]:
fit_random_forest_classifier(X_new_data, y)

0.989164662418487


0.989164662418487

In [13]:
#loop to write a tranformation X using different epsilon

for sample_eps in np.arange(0.3, 1, 0.1):
    transformer = random_projection.SparseRandomProjection(eps = 0.5)
    X_new_d = transformer.fit_transform(X_scaled)
    
    print(f"With epsilon = {sample_eps:.2f}, the transformed data has {X_new_d.shape[1]} components. The random forest achieved an accuracz of:")
    fit_random_forest_classifier(X_new_d, y)
    print("--------------------------------")

With epsilon = 0.30, the transformed data has 566 components. The random forest achieved an accuracz of:
0.98923904688701
--------------------------------
With epsilon = 0.40, the transformed data has 566 components. The random forest achieved an accuracz of:
0.9897597381666708
--------------------------------
With epsilon = 0.50, the transformed data has 566 components. The random forest achieved an accuracz of:
0.9896605588753068
--------------------------------
With epsilon = 0.60, the transformed data has 566 components. The random forest achieved an accuracz of:
0.9893878158240559
--------------------------------
With epsilon = 0.70, the transformed data has 566 components. The random forest achieved an accuracz of:
0.9893878158240559
--------------------------------
With epsilon = 0.80, the transformed data has 566 components. The random forest achieved an accuracz of:
0.9886439711388262
--------------------------------
With epsilon = 0.90, the transformed data has 566 components

In [14]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_new_pca = pca.fit_transform(X_scaled)

X_new_pca.shape

(134435, 2)

In [15]:
fit_random_forest_classifier(X_new_pca, y)

0.9152512955294935


0.9152512955294935

In [16]:
def do_pca(n_components, data):
    pca = PCA(n_components)
    X_data_pca = pca.fit_transform(data)
    return pca, X_data_pca

In [17]:
for comp in range(2, 1000):
    pca, X_data_pca = do_pca(comp, X_scaled)
    print("comp", comp)
    fit_random_forest_classifier(X_data_pca, y)
    print("-----------------------------------")

comp 2
0.913986759564603
-----------------------------------
comp 3
0.9593612853636161
-----------------------------------
comp 4
0.9724281570008182
-----------------------------------
comp 5
0.9771143785177655
-----------------------------------
comp 6
0.9816022414519848
-----------------------------------
comp 7
0.9842800823188118
-----------------------------------
comp 8
0.9851231062954056
-----------------------------------
comp 9
0.9860405147405222
-----------------------------------
comp 10
0.986809154248593
-----------------------------------
comp 11
0.9873298455282536
-----------------------------------
comp 12
0.9877017678708686
-----------------------------------
comp 13
0.9875282041109816
-----------------------------------
comp 14
0.9879745109221194
-----------------------------------
comp 15
0.9886935607845082
-----------------------------------
comp 16
0.9883216384418934
-----------------------------------
comp 17
0.989040688304282
-----------------------------------
com

comp 132
0.9909003000173564
-----------------------------------
comp 133
0.9909250948401974
-----------------------------------
comp 134
0.9913466068284942
-----------------------------------
comp 135
0.9911234534229253
-----------------------------------
comp 136
0.9909498896630383
-----------------------------------
comp 137
0.9909994793087203
-----------------------------------
comp 138
0.9907763259031515
-----------------------------------
comp 139
0.9908259155488334
-----------------------------------
comp 140
0.9908011207259925
-----------------------------------
comp 141
0.9912226327142892
-----------------------------------
comp 142
0.9907019414346284
-----------------------------------
comp 143
0.9906771466117874
-----------------------------------
comp 144
0.9910738637772433
-----------------------------------
comp 145
0.9910490689544024
-----------------------------------
comp 146
0.9910242741315614
-----------------------------------
comp 147
0.9910986586000843
------------

KeyboardInterrupt: 

In [19]:
from sklearn.decomposition import FactorAnalysis

transformer = FactorAnalysis(n_components=2, random_state=0)

X_transformed = transformer.fit_transform(X_scaled)

X_transformed.shape

(134435, 2)

In [20]:
fit_random_forest_classifier(X_transformed, y)

0.9122263271428925


0.9122263271428925

In [21]:
def do_FactorAnalysis(n_components, data):
    FA = FactorAnalysis(n_components, random_state=42)
    X_data_FA = FA .fit_transform(data)
    return FA, X_data_FA

In [23]:
for comp in range(50, 100):
    FA, X_data_FA = do_FactorAnalysis(comp, X_scaled)
    print("comp", comp)
    fit_random_forest_classifier(X_data_FA, y)
    print("-----------------------------------")

comp 50
0.9906275569661055
-----------------------------------
comp 51
0.9912226327142892
-----------------------------------
comp 52
0.9910986586000843
-----------------------------------
comp 53
0.9908755051945154
-----------------------------------
comp 54
0.9906523517889465
-----------------------------------
comp 55
0.9907515310803104
-----------------------------------
comp 56
0.9909746844858793
-----------------------------------
comp 57
0.9911730430686073
-----------------------------------
comp 58
0.9909498896630383
-----------------------------------
comp 59
0.9911978378914482
-----------------------------------
comp 60
0.9908507103716744
-----------------------------------
comp 61
0.9909250948401974
-----------------------------------
comp 62
0.9911730430686073
-----------------------------------
comp 63
0.9907515310803104
-----------------------------------
comp 64
0.9906771466117874
-----------------------------------
comp 65
0.9911730430686073
----------------------------